### ISSUE TITLE
PWA support on Chesstr

### ISSUE THREAD

**Issue by Penknife0915** [bordalix/chesstr#3]
Are there plans to add PWA support for Chesstr?

**Comment by bordalix** [comment]
I'll take a look at it during the weekend.

**Comment by bordalix** [comment]
Hey @Penknife0915, wanna give it a try?
Test environment in https://1c15745d.chesstr.pages.dev
If everything is ok, I'll push it to production

**Comment by Penknife0915** [comment]
> Hey @Penknife0915, wanna give it a try? Test environment in https://1c15745d.chesstr.pages.dev If everything is ok, I'll push it to production

I'm not a developer but as a user I haven't noticed any issue, I think it's ready.

And I want to thank you for Chesstr, it's pretty cool.

**Comment by bordalix** [comment]
Hey @Penknife0915, I'll push it to production during the weekend.

**Comment by bordalix** [comment]
Pushed to production.
